bow_match:
  custom_model_data: 123456   # <- ide a Lunar Bow CMD

homing:
  enabled: true
  range: 25.0
  turn_rate: 0.22

avoid_players:
  enabled: true
  radius: 1.5

targets:
  target_mobs: true
  ignore_shooter: true
  ignore_tamed: true
  ignore_armor_stands: true
